-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 09:41:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `new_schema` ;

-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`prefectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prefectures` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prefectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`licenses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `series` VARCHAR(45) NOT NULL,
  `conditions` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cources` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `detail` VARCHAR(45) NULL,
  `attendance_days` INT NULL,
  `fee` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`organizations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`organizations` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `new_schema`.`schools` ;

CREATE TABLE IF NOT EXISTS `new_schema`.`schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `headline` VARCHAR(45) NOT NULL,
  `overview` VARCHAR(45) NOT NULL,
  `prefecture_id` INT NOT NULL,
  `graduate_num` INT NULL,
  `begin_year` DATETIME NULL,
  `job_title_id` INT NULL,
  `location` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`prefectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`school_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school_licenses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`school_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `license_id` INT NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_license_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `new_schema`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_license_FK2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `detail` VARCHAR(45) NULL,
  `operation_company_id` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school_instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school_instructors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`school_instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NULL,
  `instructor_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `school_instructor_FK1_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_instructor_FK2_idx` (`instructor_id` ASC) VISIBLE,
  CONSTRAINT `school_instructor_FK1`
    FOREIGN KEY (`school_id`)
    REFERENCES `new_schema`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_instructor_FK2`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`instructors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cource_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cource_licenses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cource_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cource_id` INT NULL,
  `license_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cource_license_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`cources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cource_license_FK2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cource_license_FK3`
    FOREIGN KEY (`id`)
    REFERENCES `new_schema`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school_organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school_organizations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`school_organizations` (
  `id` INT NOT NULL,
  `school_id` INT NULL,
  `organization_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_organization_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `new_schema`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_organization_FK2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`business` ;

CREATE TABLE IF NOT EXISTS `mydb`.`business` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school_businesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school_businesses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`school_businesses` (
  `id` INT NOT NULL,
  `school_id` INT NULL,
  `business_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_business_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `new_schema`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_business_FK2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operation_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`operation_companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`operation_companies` (
  `id` INT NOT NULL,
  `name` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `operation_company_instructor_FK1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`instructors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school_operation_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`school_operation_companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`school_operation_companies` (
  `id` INT NOT NULL,
  `school_id` INT NULL,
  `operation_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_operation_company_FK1`
    FOREIGN KEY ()
    REFERENCES `new_schema`.`schools` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_operation_company_FK2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`operation_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job titles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job titles` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `school_job_title_FK1`
    FOREIGN KEY ()
    REFERENCES `new_schema`.`schools` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `new_schema` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
