-- MySQL Script generated by MySQL Workbench
-- Fixed version - drone school database schema
-- Model: Drone School Management System    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drone_school
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `drone_school` ;

-- -----------------------------------------------------
-- Schema drone_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drone_school` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `drone_school` ;

-- -----------------------------------------------------
-- Table `drone_school`.`prefectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`prefectures` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`prefectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`job_titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`job_titles` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`job_titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`licenses` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `series` VARCHAR(45) NOT NULL,
  `conditions` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`organizations` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`organizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`business`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`business` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`operation_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`operation_companies` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`operation_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`schools` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `headline` VARCHAR(200) NOT NULL,
  `overview` TEXT NOT NULL,
  `prefecture_id` INT NOT NULL,
  `graduate_num` INT NULL,
  `begin_year` YEAR NULL,
  `job_title_id` INT NULL,
  `location` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `school_prefecture_FK_idx` (`prefecture_id` ASC) VISIBLE,
  INDEX `school_job_title_FK_idx` (`job_title_id` ASC) VISIBLE,
  CONSTRAINT `school_prefecture_FK`
    FOREIGN KEY (`prefecture_id`)
    REFERENCES `drone_school`.`prefectures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_job_title_FK`
    FOREIGN KEY (`job_title_id`)
    REFERENCES `drone_school`.`job_titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`courses` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `detail` TEXT NULL,
  `attendance_days` INT NULL,
  `fee` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`instructors` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `detail` TEXT NULL,
  `operation_company_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `instructor_operation_company_FK_idx` (`operation_company_id` ASC) VISIBLE,
  CONSTRAINT `instructor_operation_company_FK`
    FOREIGN KEY (`operation_company_id`)
    REFERENCES `drone_school`.`operation_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`school_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`school_licenses` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`school_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `license_id` INT NOT NULL,
  `status` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `school_license_school_FK_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_license_license_FK_idx` (`license_id` ASC) VISIBLE,
  CONSTRAINT `school_license_school_FK`
    FOREIGN KEY (`school_id`)
    REFERENCES `drone_school`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_license_license_FK`
    FOREIGN KEY (`license_id`)
    REFERENCES `drone_school`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`school_instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`school_instructors` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`school_instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `school_instructor_school_FK_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_instructor_instructor_FK_idx` (`instructor_id` ASC) VISIBLE,
  CONSTRAINT `school_instructor_school_FK`
    FOREIGN KEY (`school_id`)
    REFERENCES `drone_school`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_instructor_instructor_FK`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `drone_school`.`instructors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`course_licenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`course_licenses` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`course_licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `license_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `course_license_course_FK_idx` (`course_id` ASC) VISIBLE,
  INDEX `course_license_license_FK_idx` (`license_id` ASC) VISIBLE,
  CONSTRAINT `course_license_course_FK`
    FOREIGN KEY (`course_id`)
    REFERENCES `drone_school`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_license_license_FK`
    FOREIGN KEY (`license_id`)
    REFERENCES `drone_school`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`school_organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`school_organizations` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`school_organizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `organization_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `school_organization_school_FK_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_organization_organization_FK_idx` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `school_organization_school_FK`
    FOREIGN KEY (`school_id`)
    REFERENCES `drone_school`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_organization_organization_FK`
    FOREIGN KEY (`organization_id`)
    REFERENCES `drone_school`.`organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`school_businesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`school_businesses` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`school_businesses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `school_business_school_FK_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_business_business_FK_idx` (`business_id` ASC) VISIBLE,
  CONSTRAINT `school_business_school_FK`
    FOREIGN KEY (`school_id`)
    REFERENCES `drone_school`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_business_business_FK`
    FOREIGN KEY (`business_id`)
    REFERENCES `drone_school`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `drone_school`.`school_operation_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `drone_school`.`school_operation_companies` ;

CREATE TABLE IF NOT EXISTS `drone_school`.`school_operation_companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `operation_company_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `school_operation_company_school_FK_idx` (`school_id` ASC) VISIBLE,
  INDEX `school_operation_company_operation_FK_idx` (`operation_company_id` ASC) VISIBLE,
  CONSTRAINT `school_operation_company_school_FK`
    FOREIGN KEY (`school_id`)
    REFERENCES `drone_school`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `school_operation_company_operation_FK`
    FOREIGN KEY (`operation_company_id`)
    REFERENCES `drone_school`.`operation_companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
